# Generated by Django 4.0.6 on 2022-07-05 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=100, null=True)),
                ('book_title', models.CharField(blank=True, max_length=300, null=True)),
                ('book_author', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField(default=datetime.date(2022, 7, 6))),
                ('total_quantity', models.BooleanField()),
                ('available_quantity', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
